# Generated by Django 4.2.5 on 2025-01-20 09:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='instructors/')),
                ('rpc_number', models.CharField(max_length=50)),
                ('experience', models.TextField()),
                ('issued_date', models.DateField()),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('drone_details', models.TextField()),
                ('slot_date', models.DateField(editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.bookingslot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userbooking',
            constraint=models.UniqueConstraint(fields=('email', 'phone_number', 'slot_date'), name='unique_booking_per_day_per_user'),
        ),
    ]
